Ev_charging/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("users_app.urls")),
    path('',include("station_app.urls")),
    path('admin_app/',include("admin_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_signin, name='admin_signin'),
    path('admin_signout/', views.admin_signout, name='admin_signout'),  # Corrected with trailing slash
    path('dashboard/', views.dashboard, name='dashboard'),
    path('approvestation/<int:s_id>/', views.approvestation, name='approvestation'),
    path('removestation/<int:s_id>/', views.removestation, name='removestation'),
    path('all_bookings/',views.all_bookings,name="all_bookings"),
]

users_app/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from station_app.models import Station

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=10)
    age = models.IntegerField()
    vehicle_no=models.CharField(max_length=200,null=True,blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True)


    def __str__(self):
        return self.user.username

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    station = models.ForeignKey(Station, on_delete=models.CASCADE, related_name='bookings', null=True)
    slot_number = models.IntegerField(null=True)  # Modified
    start_time = models.CharField(max_length=10,null=True)
    end_time = models.CharField(max_length=10,null=True)
    date = models.DateField(null=True)
    phone_number = models.CharField(max_length=15)
    booked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booked_items', null=True)
    status = models.CharField(max_length=20, default='Pending')

from station_app.models import StationProfile
class Message(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    station=models.ForeignKey(StationProfile,on_delete=models.CASCADE,null=True,blank=True)
    added_Date = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=200,null=True,blank=True)
    reply = models.BooleanField(default=False)

templates/users/booking.html
{% extends "users/viewpage.html" %}
{% block content %}
<h1 class="text-center text-primary-emphasis">Book Slot</h1>

{% if form.errors %}
<ul>
    {% for field, errors in form.errors.items %}
    <li><strong>{{ field }}:</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:100px;top:10px"
    role="alert">
    <strong>{{message}} !!!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="border border-dark p-5 rounded-4 border-0 shadow-lg container col-md-6 mx-auto w-4" style="width: 400px; margin: auto;">
    <form method="post">
        {% csrf_token %}
        <label for="id_date" class="text-primary">Date:</label>
        <input type="date" name="date" id="id_date" required><br><br>

        <label for="id_start_time" class="text-primary">Start Time:</label>
        <input type="text" name="start_time" id="id_start_time" required><br><br>

        <label for="id_end_time" class="text-primary">End Time:</label>
        <input type="text" name="end_time" id="id_end_time" required><br><br>

        <label for="id_phone_number" class="text-primary">Phone Number:</label>
        <input type="text" name="phone_number" id="id_phone_number" required><br><br>

        <label for="id_slot_number" class="text-primary">Slot Number:</label>
        <select name="slot_number" id="id_slot_number" required>
            <option value="">Select Slot Number</option>
            {% for slot in available_slots %}
            <option value="{{ slot }}">{{ slot }}</option>
            {% endfor %}
        </select><br><br>

        <button type="submit" class="btn rounded-pill btn-dark">Book Slot</button>
    </form>
</div>
{% endblock %}

templates/users/booking_details.html
{% extends "users/viewpage.html" %}
{%load static%}
{% block content %}
<div class="container">

        <button id="pay-button" class="button  mt-2 razorpay" style="border: none; background-color: rgb(66, 183, 222); border-radius: 5px; padding: 5px;">
          <span>
              <img src="{%static '/img/razor.png' %}" height="30px" width="50px" alt="" class="me-2" style="margin-top: 10px; ">
              Pay Now
          </span>
      </button>
    <h1>Booking Details</h1>


    {% if user_bookings %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Station Name</th>
                    <th>Slot Number</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Date</th>
                    <th>Phone Number</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for booking in user_bookings %}
                <tr>
                    <td>{{ booking.station.station_name }}</td>
                    <td>{{ booking.slot_number }}</td>
                    <td>{{ booking.start_time }}</td>
                    <td>{{ booking.end_time }}</td>
                    <td>{{ booking.date }}</td>
                    <td>{{ booking.phone_number }}</td>
                    <td> <form action="{% url 'cancel_booking' booking.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Cancel</button>
                    </form></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>No bookings found.</p>
    {% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        key: 'rzp_test_9tCOZuKLhiZdaM',
        amount: 500, // Amount in paise (50000 paise = ₹500)
        currency: 'INR',
        name: 'Demo Store',
        description: 'Payment for your order',
        image: 'https://example.com/logo.png', // URL of your store's logo
        order_id: '{{ razorpay_order_id }}', // Replace with your actual order ID
        callback_url: '{{ callback_url }}', // Replace with your actual callback URL
        prefill: {
            name: 'student',
            email: 'student@example.com'
        }
    };

    var rzp = new Razorpay(options);

    document.getElementById('pay-button').onclick = function () {
        rzp.open();
    };
</script>
{%endblock%}

templates/users/build_profile.html
{%extends "users/viewpage.html" %}
{% block content %}
<div class="container mx-auto col-md-6 mt-5 mb-5" style="border: 1px solid black;">
<h1>Build Your Profile</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save Profile</button>
</form>
</div>
{% endblock %}

templates/users/login.html
{% extends "index.html" %}
{% block content %}
<style>
    .form-label {
        color: rgb(241, 39, 21);
    }

    .link {
        font-weight: bold;
        color: #271212; /* Change color as needed */
    }

    .link:hover {
        color: rgb(69, 52, 52);
        text-decoration: none;
    }
</style>
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:100px;top:10px"
    role="alert">
    <strong>{{message}} !!!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="container" style="margin-top: 15px;">
        <div class="row justify-content-center align-items-center">
            <div class="col-lg-5">
                <div class=" py-5 px-4 px-sm-5" style="border-radius: 15px; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
                    <form class="py-5" action="{% url 'signin' %}" method="post">
                        {% csrf_token %}
                        <div class="text-center">
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form1Example1">Username</label>
                            <input type="text" id="form1Example1" name="username" class="form-control" />
                        </div>
                        
                        <!-- Password input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="form1Example2">Password</label>
                            <input type="password" id="form1Example2" name="password" class="form-control" />
                        </div>
                        
                        <div>
                            <button class="btn btn-dark btn-block border-0 py-2" type="submit" style="max-width: 150px; margin-left: 100px;">Login</button>
                        </div>
                        </div><br>
                        <p class="text-center text-dark">Don't have an account? <a href="{% url 'signup' %}" class="link">Register Here</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/signup.html
{% extends "index.html" %}
{% block content %}
<style>
    /* Style for the label */
    .link {
        font-weight: bold;
        color: #333;
    }

    .link:hover {
        color: rgb(37, 25, 25);
        text-decoration: none;
    }

    /* Style for the fields */
    .label-tag {
        color: rgb(241, 39, 21);
    }
    .form-group select,
    .form-group input[type="text"],
    .form-group input[type="email"],
    .form-group input[type="password"] {
        width: 80%;
        border: 1px solid rgb(173, 173, 173);
        padding: 8px;
        margin: 5px 0;
        border-radius: 5px;
    
    }
</style>
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:100px;top:10px"
    role="alert">
    <strong>{{message}} !!!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% if form.errors %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index:-1;right:40px;top:200px"
    role="alert">
    <strong>{{form.errors}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

<div class="d-flex justify-content-center align-items-center " style="height: 100vh; border-radius: 30px;">
    <div class="container mt-5 p-3" style="border-radius: 30px;">

        <div class="row justify-content-center align-items-center">
            <div class="col-md-6" style="border-radius: 30px;">
                <div class=" py-2 px-3 px-sm-3" style="border-radius:15px; box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
                    <form class="py-5" action="" method="POST">
                        {% csrf_token %}
                        <div class="text-center"> <!-- Center the form fields and labels -->
                            {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="label-tag">{{ field.label }}:</label><br>
                                {{ field }}
                            </div>
                            {% endfor %}
                        </div>
                        <div>
                            <button class="btn btn-dark btn-block border-0 py-2" type="submit" style="max-width: 150px; align-items: center; margin-left: 175px;">Register</button>
                        </div><br>
                        <p class="text-center text-dark">Already have an account? <a href="{% url 'signin' %}" class="link">Login Here</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/station_profile.html
{% extends "users/viewpage.html" %}
{% load static %}

{% block content %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:100px;top:10px"
    role="alert">
    <strong>{{message}} !!!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container mt-5">
    <h2>Station Profiles</h2>
    <div class="row">
      {% for profile in station_profiles %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <img src="{{ profile.Profile_Image.url }}" class="card-img-top" alt="{{ profile.user.username }}" height="200"  >
          <div class="card-body">
            <h5 class="card-title">{{ profile.user.username }}</h5>
            <p class="card-text"><strong>Address:</strong> {{ profile.Address }}</p>
            <p class="card-text"><strong>Phone Number:</strong> {{ profile.Phone_Number }}</p>
           
            <!-- Add other profile fields as needed -->

            <p class="my-3 font-weight-bold">Send Message to station</p>
            <form action="{% url 'send_message'  profile.user.id %}" class="d-flex align-items-center" method="post">
                {% csrf_token %}
                <input type="text" class="w-75 border-secondary mr-2 p-2" name="message" placeholder="Enter message here..">
                <button class="btn btn-primary">Send</button>
            </form>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>

{% endblock %}

templates/users/user_booking.html
{% if error_message %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:80px;top:30px"
  role="alert">
  <strong>{{ error_message }} !!!</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="book_form justify-content-center align-items-center" style="box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 15px 0px; padding: 10px; max-width: 500px;">
<form method="post" action="{% url 'book_turf' turf.Turf_ID %}">
  {% csrf_token %}

  
<br>
  <label for="id_date">Date:</label>
  <input type="date" name="date" id="id_date" required>
<br>
  <label for="id_start_time">Start Time:</label>
  <input type="time" name="start_time" id="id_start_time" required>

  <input type="hidden" name="timezone_offset" id="timezone_offset">

<br>  

  <label for="id_end_time">End Time:</label>
  <input type="time" name="end_time" id="id_end_time" required>

<br>

  <label for="id_phone_number">Phone Number:</label>
  <input type="text" name="phone_number" id="id_phone_number" required>

  <br>

  

  <button type="submit">Book Now</button>
</form>
</div>
<script>
  // Get the current timezone offset and set it as the value of the hidden input
  document.getElementById('timezone_offset').value = new Date().getTimezoneOffset();
</script>


{%endblock%}

templates/users/view-messages.html
{% extends "users/viewpage.html" %}
{% load static %}

{% block content %}
<style>
    .inbox-card {
        background: linear-gradient(to right, #c9f1dd, #c9f1dd);
        border-radius: 15px;
        max-width: 400px;
        margin-left: 50px;
        

    }

    .outbox-card {
        background: linear-gradient(to right,#b6c5c0,#b6c5c0);
        color: rgb(99, 103, 107);
        border-radius: 15px;
        max-width: 400px;
        
    }

    .badge {
        border-radius: 50%;
        background: rgb(240, 102, 70);
        padding: 5px 20px;
        margin-left: 50px;
    }
</style>
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show" style="position: fixed;z-index: 90;right:100px;top:10px"
    role="alert">
    <strong>{{message}} !!!</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<h2 class="title-subhny mb-2 text-center">View Messages </h2>
<section class="w3l-bottom-grids-6 py-5" id="services">
    <div class="container py-lg-5 py-md-4 py-2">
        
        <div class="row">
            <div class="col-6">

                {% if user_messages_count == 0 %}
                <h3><span>No Outbox Messages Found</span></h3>
                {% else %}
                <h3 class="text-center"><span>Outbox</span><span class="badge">{{user_messages_count}}
                    </span></h3>
                <div class="grids-area-hny main-cont-wthree-fea row pt-5 mt-5">
                    {% for v in user_messages %}
                    <div class="col-12  mb-3 shadow-sm p-2 inbox-card">
                        <div class="d-flex align-items-center justify-content-between">
                          {%comment%}
                            <img src="{{v.company.station_image.url}}" width="50" style="border-radius: 50%;" alt="">
                            {%endcomment%}
                            <h5>{{v.message}}</h5>
                        </div>
                        <div class="text-right">
                          <p>To :<span class="font-weight-bold">{{ v.station.user.username }} </span></p>

                            <p>on :<span class="font-weight-bold">{{v.added_Date}} </span></p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="col-6">

                {% if reply_messages_count == 0 %}
                <h3><span>No Inbox Messages Found</span> </h3>
                {% else %}
                <h3 class="text-center"><span>Inbox</span> <span class="badge"> {{reply_messages_count}} </span>
                </h3>
                <div class="grids-area-hny main-cont-wthree-fea row pt-5 mt-5">
                    {% for v in reply_messages %}
                    <div class="col-12  mb-3 shadow-sm p-2 outbox-card">
                        <div class="d-flex align-items-center justify-content-between">
                            <img src="{{v.company.station_image.url}}" width="50" style="border-radius: 50%;" alt="">
                            <h5>{{v.message}}</h5>
                        </div>
                        <div class="text-right">
                            <p>From :<span class="font-weight-bold">{{ v.station.user.username }} </span></p>
                            <p>on :<span class="font-weight-bold">{{v.added_Date}} </span></p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{%endblock%}

templates/users/view_profile.html
 {%extends "users/viewpage.html"%}
 
 <style>
    .header{
      background-color:#075B4C ;
      color: blueviolet;
    }
    
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }

        .room-container {
    display: flex;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}

.sidebar {
    width: 25%;
    background-color: #f8f1f1;
    color: rgb(11, 109, 76);
    padding: 1px;
}

.content {
    flex-grow: 1;
    padding: 20px;
}

.room-box {
    background-color: #fff;
    padding: 10px;
    margin-bottom: 2px;
    border-radius: 5px;
}

h2 {
    color: #333;
}

p {
    color: #666;
}
.book-now-button {
            display: block;
            margin-top: 10px;
            padding: 8px 12px;
            background-color: #036555;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            max-width: 100px;
        }
        .room-box {
            background-color: #fff;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .room-card {
            display: flex;
            background-color: #fff;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .room-image {
            max-width: 200px;
            margin-right: 20px;
            border-radius: 5px 0 0 5px;
            overflow: hidden;
        }

        .room-image img {
            width: 100%;
            height: auto;
        }

        .room-details {
            flex-grow: 1;
            padding: 15px;
        }

@media (max-width: 768px) {
    .room-container {
        flex-direction: column;
    }

    .sidebar,
    .content {
        width: 100%;
    }
}
    </style>
 
{% block content %}
<div class="container-fluid">
  <div class="row">
      <!-- Sidebar -->
       <!-- Sidebar -->
    <div class="col-md-3">
      <div class="container mt-5">
        <ul class="list-group">
          
          <li class="list-group-item">
              <a class="nav-link" href="" style="color: #075B4C;">Notifications {% if notifications %}<span style="color: rgb(234, 125, 41); font-size: 20px;">{{ notifications|length }}</span> {%endif%}</a>
          </li>
          
         
          <li class="list-group-item">
            <a class="nav-link" href="" style="color: #075B4C;">Add Feedback</a>
          </li>
          <li class="list-group-item">
            <a class="nav-link" href="" style="color: #075B4C;">View Feedback</a>
          </li>
          <li class="list-group-item">
            <a class="nav-link" href="" style="color: #075B4C;">View Staff</a>
          </li>
          
          <li class="list-group-item">
            {% if request.user.userprofile %}
              <a class="nav-link" href="{% url 'view_profile' username=request.user.username %}" style="color: #075B4C;">Profile</a>
            {% else %}
              <a class="nav-link" href="{% url 'build_profile' %}" style="color: #075B4C;">Build Profile</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
    
      <!-- Main Content -->
      <div class="col-md-9">
          <div class="container col-md-6 mt-5 mb-5 p-5" style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px; border-radius: 10px;">
              <h1>{{ user.username }}'s Profile</h1>
              {% if profile.profile_photo %}
                  <img src="{{ profile.profile_photo.url }}" alt="{{ user.username }}'s Profile Photo" style="height: 80px; width: 80px; border-radius: 50px;">
              {% endif %}
              
              <p><strong>Location:</strong> {{ profile.location }}</p>
              <p><strong>Address:</strong> {{ profile.address }}</p>
              <p><strong>Vehicle no:</strong> {{ profile.vehicle_no }}</p>
      
              <p><strong>Phone Number:</strong> {{ profile.phone_number }}</p>
              <p><strong>Age:</strong> {{ profile.age }}</p>
          </div>
      </div>
  </div>
</div>
</div>


{% endblock %}

templates/users/viewdetails.html
{% extends "users/viewpage.html" %}
{% load static %}

{% block content %}
<div class="container mt-3">
    <div class="row">
      <div class="col-lg my-2 d-flex align-items-center">
        {% if station.station_image %}
          <img src="{{ station.station_image.url }}" class="img-fluid" alt="Turf Image" style="max-height: 300px; width: 50%;">
        {% endif %}
        <div class="text-center ml-5">
          <p style="color: darkgreen; font-family: 'Edu TAS Beginner', cursive; font-size: 2rem; text-transform: capitalize;">{{station.station_name}}</p>
          <h5> {{ station.station_caption }}</h5>
          <p>Slots: {{ station.slots }}</p>
          <p>Price: ₹{{ station.station_price }}</p>
          <p>Address: {{ station.station_address }}</p>
          <p>Phone No: {{ station.station_phone }}</p>
          <p>Email: {{ station.station_email }}</p>
          <p>Area: {{ station.station_area }}</p>
          <a href="{%url 'station_profile' %}" class="btn btn-success mt-4">Enquire Now</a>
          <a href="{% url 'book_slot' station.station_ID %}" class="btn btn-primary mt-4">Book Now</a>
        </div>
      </div>
    </div>
</div>

{% endblock %}